name: Publish distube
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: yarn.lock
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn --immutable

      - name: Change version to ${{ github.event.release.tag_name }}
        run: yarn version ${{ github.event.release.tag_name }}

      - name: Publish
        run: yarn npm publish --access public --tag latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Deprecate older versions
        run: npm deprecate distube@"< ${{ github.event.release.tag_name }}" "This version is deprecated, please upgrade to the latest version."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
